In [1]:
import numpy as np

## Question 1

<img src="images/otc_pagerank2.gif">

Suppose we compute PageRank with a ß of 0.7, and we introduce the additional constraint that the sum of the PageRanks of the three pages must be 3, to handle the problem that otherwise any multiple of a solution will also be a solution. Compute the PageRanks a, b, and c of the three pages A, B, and C, respectively.

Then, identify from the list below, the true statement.

1. a + c = 2.745
2. a + c = 1.985
3. b + c = 2.7
4. a + b = 0.655

v' = ßMv + (1 - ß)(e/n)

In [2]:
M1 = np.array([0., 0., 0., .5, 0., 0., .5, 1., 1.]).reshape((3,3))
M1

array([[ 0. ,  0. ,  0. ],
       [ 0.5,  0. ,  0. ],
       [ 0.5,  1. ,  1. ]])

In [3]:
# the sum of the PageRanks of the three pages must be 3
# v0 = np.array([1., 1., 1.]).reshape((3,1))
v0 = np.ones((3,1))
v0

array([[ 1.],
       [ 1.],
       [ 1.]])

In [4]:
# teleport / random surfer
beta = 0.7

# e / n
# ones = np.ones(3).reshape((3,1))
ones = np.ones((3,1))
e_div_n = ones * 1./3.
surfer = e_div_n * (1. - beta)
surfer

array([[ 0.1],
       [ 0.1],
       [ 0.1]])

In [5]:
v_test = range(1, 21)
rank_list = []

rank_list.append(v0)

In [6]:
for i in v_test:
    v_prime = beta * np.dot(M1, rank_list[i - 1]) + surfer
    # re-insert the leaked PageRank
    leaked = 3. - sum(v_prime)
    re_insert = np.ones((3,1)) * leaked/3.
    v_prime = np.add(v_prime, re_insert)
    rank_list.append(v_prime)

In [7]:
rank_list[-1]

array([[ 0.3  ],
       [ 0.405],
       [ 2.295]])

In [8]:
## b + c = 2.7

## Question 2

<img src="images/otc_pagerank3.gif">

Suppose we compute PageRank with ß=0.85. Write the equations for the PageRanks a, b, and c of the three pages A, B, and C, respectively. Then, identify in the list below, one of the equations.

// do not run cell //
.95c = .9b + .475a
a = .9c + .05b
b = .575a + .15c
c = b + .575a

v' = ßMv + (1 - ß)(e/n)

In [9]:
M2 = np.array([0., 0., 1., .5, 0., 0., .5, 1., 0.]).reshape((3,3))
M2

array([[ 0. ,  0. ,  1. ],
       [ 0.5,  0. ,  0. ],
       [ 0.5,  1. ,  0. ]])

In [10]:
beta2 = .85
v0_2 = np.ones((3,1)) * 1./3.
surfer2 = (1. - beta2) * np.ones((3,1)) * 1./3.
beta2, v0_2, surfer2

(0.85, array([[ 0.33333333],
        [ 0.33333333],
        [ 0.33333333]]), array([[ 0.05],
        [ 0.05],
        [ 0.05]]))

In [11]:
v_test2 = range(1, 31)
rank_list2 = []

rank_list2.append(v0_2)

In [12]:
rank_list2

[array([[ 0.33333333],
        [ 0.33333333],
        [ 0.33333333]])]

In [13]:
for i in v_test2:
    v_prime = beta2 * np.dot(M2, rank_list2[i - 1]) + surfer2
    # re-insert the leaked PageRank
    leaked = 1. - sum(v_prime)
    re_insert = np.ones((3,1)) * leaked/3.
    v_prime = np.add(v_prime, re_insert)
    rank_list2.append(v_prime)

In [14]:
len(rank_list2)

31

In [15]:
pageranks2 = rank_list2[-1]
pageranks2

array([[ 0.38778967],
       [ 0.21481064],
       [ 0.39739969]])

In [16]:
a = pageranks2[0][0]
b = pageranks2[1][0]
c = pageranks2[2][0]
a, b, c

(0.38778966918159774, 0.21481064239242184, 0.39739968842598039)

In [32]:
# close enough!
# round to get approximate equation

float("%.5f" % (.95*c)) == float("%.5f" % (.9*b + .475*a)), .95*c, .9*b + .475*a

(True, 0.37752970400468133, 0.37752967101443857)

In [18]:
a == .9*c + .05*b, a, .9*c + .05*b

(False, 0.38778966918159774, 0.3684002517030035)

In [19]:
b == .575*a + .15*c, b, .575*a + .15*c

(False, 0.21481064239242184, 0.28258901304331574)

In [20]:
c == b + .575*a, c, b + .575*a

(False, 0.39739968842598039, 0.43778970217184054)

In [ ]:
## .95c = .9b + .475a

## Question 3

<img src="images/otc_pagerank3 (1).gif">

Assuming no "taxation," compute the PageRanks a, b, and c of the three pages A, B, and C, using iteration, starting with the "0th" iteration where all three pages have rank a = b = c = 1. Compute as far as the 5th iteration, and also determine what the PageRanks are in the limit. Then, identify the true statement from the list below.

// do not run cell //
After iteration 4, a = 9/8
In the limit, c = 4/3
In the limit, c = 6/5
In the limit, a = 5/4

In [37]:
M3 = np.array([0., 0., 1., .5, 0., 0., .5, 1., 0.]).reshape((3,3))
M3

array([[ 0. ,  0. ,  1. ],
       [ 0.5,  0. ,  0. ],
       [ 0.5,  1. ,  0. ]])

In [38]:
v0_3 = np.ones((3,1))
v0_3

array([[ 1.],
       [ 1.],
       [ 1.]])

In [47]:
v_test3 = range(1, 101)
rank_list3 = []

rank_list3.append(v0_3)

In [48]:
for i in v_test3:
    v_prime = np.dot(M3, rank_list3[i-1])
    rank_list3.append(v_prime)

In [49]:
rank_list3[4]

array([[ 1.25],
       [ 0.5 ],
       [ 1.25]])

In [51]:
rank_list3[-1]

array([[ 1.2],
       [ 0.6],
       [ 1.2]])

In [ ]:
## In the limit, c = 6/5

## Question 4

Suppose our input data to a map-reduce operation consists of integer values (the keys are not important). The map function takes an integer i and produces the list of pairs (p,i) such that p is a prime divisor of i. For example, map(12) = [(2,12), (3,12)].
The reduce function is addition. That is, reduce(p, [i1, i2, ...,ik]) is (p,i1+i2+...+ik).

Compute the output, if the input is the set of integers 15, 21, 24, 30, 49. Then, identify, in the list below, one of the pairs in the output.

// do not run cell // 
(7,119)
(2,102)
(3,69)
(3,90)

In [75]:
from collections import defaultdict

In [52]:
input = [15, 21, 24, 30, 49]

In [80]:
map_dict = {}


# correct answer derived
# BUT
# the inner-most for-loop to identify prime factors is faulty:
# leaving out '2' as a factor AND including '15' as a prime factor
for i in input:
    map_dict[i] = []
    # print i, range(2, i)
    for j in range(2, i):
        if i%j == 0:
            # print j, range(2, j)
            for k in (2,j):
                if j%k == 0:
                    break
                else:
                    map_dict[i].append((j, i))
        
map_dict

{15: [(3, 15), (5, 15)],
 21: [(3, 21), (7, 21)],
 24: [(3, 24)],
 30: [(3, 30), (5, 30), (15, 30)],
 49: [(7, 49)]}

In [70]:
u, v = map_dict[15][0][0], map_dict[15][0][1]
v

15

In [77]:
output = {}

for k in map_dict:
    for i in range(len(map_dict[k])):
        if map_dict[k][i][0] not in output:
            output[map_dict[k][i][0]] = map_dict[k][i][1]
        else:
            output[map_dict[k][i][0]] += map_dict[k][i][1]
        
output

{3: 90, 5: 45, 7: 70, 15: 30}

In [ ]:
## (3,90)