In [10]:
import pandas as pd
import numpy as np

## Question 1

<img src="images/3a_1.JPG">

Write the adjacency matrix A, the degree matrix D, and the Laplacian matrix L. For each, find the sum of all entries and the number of nonzero entries. Then identify the true statement from the list below.

The sum of the entries of D is 11.<br>
The sum of the entries of D is 0.<br>
D has 16 nonzero entries.<br>
The sum of the entries of L is 0.

In [8]:
# adjacency matrix A
A = np.matrix([
        #A, B, C, D, E, F, G, H
        [0, 0, 1, 0, 0, 1, 0, 0], # A
        [0, 0, 0, 0, 1, 0, 0, 1], # B
        [1, 0, 0, 1, 0, 1, 0, 0], # C
        [0, 0, 1, 0, 1, 0, 1, 0], # D
        [0, 1, 0, 1, 0, 0, 0, 1], # E 
        [1, 0, 1, 0, 0, 0, 1, 0], # F
        [0, 0, 0, 1, 0, 1, 0, 1], # G
        [0, 1, 0, 0, 1, 0, 1, 0]  # H
    ])

A

matrix([[0, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 1],
        [1, 0, 0, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 0, 1],
        [0, 1, 0, 0, 1, 0, 1, 0]])

In [9]:
# degree matrix D
D = np.matrix([
        #A, B, C, D, E, F, G, H
        [2, 0, 0, 0, 0, 0, 0, 0], # A
        [0, 2, 0, 0, 0, 0, 0, 0], # B
        [0, 0, 3, 0, 0, 0, 0, 0], # C
        [0, 0, 0, 3, 0, 0, 0, 0], # D
        [0, 0, 0, 0, 3, 0, 0, 0], # E
        [0, 0, 0, 0, 0, 3, 0, 0], # F
        [0, 0, 0, 0, 0, 0, 3, 0], # G
        [0, 0, 0, 0, 0, 0, 0, 3]  # H
    ])

D

matrix([[2, 0, 0, 0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0, 0],
        [0, 0, 0, 3, 0, 0, 0, 0],
        [0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 3, 0],
        [0, 0, 0, 0, 0, 0, 0, 3]])

In [10]:
# Laplacian matrix L
L = D - A
L

matrix([[ 2,  0, -1,  0,  0, -1,  0,  0],
        [ 0,  2,  0,  0, -1,  0,  0, -1],
        [-1,  0,  3, -1,  0, -1,  0,  0],
        [ 0,  0, -1,  3, -1,  0, -1,  0],
        [ 0, -1,  0, -1,  3,  0,  0, -1],
        [-1,  0, -1,  0,  0,  3, -1,  0],
        [ 0,  0,  0, -1,  0, -1,  3, -1],
        [ 0, -1,  0,  0, -1,  0, -1,  3]])

## answer: The sum of the entries of L is 0.

## Question 2

<img src="images/3a_2.JPG">

The goal is to find two clusters in this graph using Spectral Clustering on the Laplacian matrix. Compute the Laplacian of this graph. Then compute the second eigen vector of the Laplacian (the one corresponding to the second smallest eigenvalue).

To cluster the points, we decide to split at the mean value. We say that a node is a tie if its value in the eigen-vector is exactly equal to the mean value. Let's assume that if a point is a tie, we choose its cluster at random. Identify the true statement from the list below.

1 and 3 in the same cluster<br>
3 and 5 can either be in the same cluster or in different clusters (depending on randomness)<br>
3 is a tie<br>
2 and 5 are in different clusters

In [12]:
# adjacency matrix 
A2 = np.matrix([
        #1, 2, 3, 4, 5, 6
        [0, 1, 1, 0, 0, 0], # 1
        [1, 0, 0, 1, 0, 1], # 2
        [1, 0, 0, 1, 0, 0], # 3
        [0, 1, 1, 0, 1, 0], # 4
        [0, 0, 0, 1, 0, 1], # 5
        [0, 1, 0, 0, 1, 0] # 6
    ])
A2

matrix([[0, 1, 1, 0, 0, 0],
        [1, 0, 0, 1, 0, 1],
        [1, 0, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [0, 0, 0, 1, 0, 1],
        [0, 1, 0, 0, 1, 0]])

In [13]:
D2 = np.matrix([
        #1, 2, 3, 4, 5, 6
        [2, 0, 0, 0, 0, 0], # 1
        [0, 3, 0, 0, 0, 0], # 2
        [0, 0, 2, 0, 0, 0], # 3
        [0, 0, 0, 3, 0, 0], # 4
        [0, 0, 0, 0, 2, 0], # 5
        [0, 0, 0, 0, 0, 2]  # 6
    ])

D2

matrix([[2, 0, 0, 0, 0, 0],
        [0, 3, 0, 0, 0, 0],
        [0, 0, 2, 0, 0, 0],
        [0, 0, 0, 3, 0, 0],
        [0, 0, 0, 0, 2, 0],
        [0, 0, 0, 0, 0, 2]])

In [14]:
L2 = D2 - A2
L2

matrix([[ 2, -1, -1,  0,  0,  0],
        [-1,  3,  0, -1,  0, -1],
        [-1,  0,  2, -1,  0,  0],
        [ 0, -1, -1,  3, -1,  0],
        [ 0,  0,  0, -1,  2, -1],
        [ 0, -1,  0,  0, -1,  2]])

In [16]:
from numpy import linalg as LA

In [30]:
w,v = LA.eig(L2)
w

array([  5.00000000e+00,  -4.17038366e-16,   1.00000000e+00,
         2.00000000e+00,   3.00000000e+00,   3.00000000e+00])

In [36]:
v[:,2], np.mean(v[:,2])

for i in v[:,2]:
    print i, i < np.mean(v[:,2])

[[-0.5]] [[ True]]
[[ -2.23361253e-16]] [[ True]]
[[-0.5]] [[ True]]
[[  5.77149001e-17]] [[False]]
[[ 0.5]] [[False]]
[[ 0.5]] [[False]]


## Question 3

We wish to estimate the surprise number (2nd moment) of a data stream, using the method of AMS. It happens that our stream consists of ten different values, which we'll call 1, 2,..., 10, that cycle repeatedly. That is, at timestamps 1 through 10, the element of the stream equals the timestamp, at timestamps 11 through 20, the element is the timestamp minus 10, and so on. It is now timestamp 75, and a 5 has just been read from the stream. As a start, you should calculate the surprise number for this time.
For our estimate of the surprise number, we shall choose three timestamps at random, and estimate the surprise number from each, using the AMS approach (length of the stream times 2m-1, where m is the number of occurrences of the element of the stream at that timestamp, considering all times from that timestamp on, to the current time). Then, our estimate will be the median of the three resulting values.

You should discover the simple rules that determine the estimate derived from any given timestamp and from any set of three timestamps. Then, identify from the list below the set of three "random" timestamps that give the closest estimate.

{3, 45, 72}<br>
{20, 49, 53}<br>
{30, 47, 62}<br>
{4, 31, 72}

In [49]:
n = 75
sec_moment = 0
for i in range(1,11):
    if i <= 5:
        sec_moment += (i**2)*8
    else:
        sec_moment += (i**2)*7
    print i, i**2, sec_moment
        
        
sec_moment

1 1 8
2 4 40
3 9 112
4 16 240
5 25 440
6 36 692
7 49 1035
8 64 1483
9 81 2050
10 100 2750


2750

In [40]:
random = {1: {3, 45, 72},
          2: {20, 49, 53},
          3: {30, 47, 62},
          4: {4, 31, 72}}

In [50]:
print n*(2*8-1)+n*(2*4-1)+n*(2*1-1)
print n*(2*6-1)+n*(2*3-1)+n*(2*3-1)
print n*(2*5-1)+n*(2*3-1)+n*(2*2-1)
print n*(2*8-1)+n*(2*5-1)+n*(2*1-1)

1725
1575
1275
1875


In [52]:
for k in random:
    for v in random[k]:
        print 75 - v, (75 - v) // 10

3 0
72 7
30 3
26 2
55 5
22 2
45 4
13 1
28 2
3 0
71 7
44 4


<img src="images/explain3a_3.JPG">

## Question 4

We wish to use the Flagolet-Martin lgorithm of Section 4.4 to count the number of distinct elements in a stream. Suppose that there ten possible elements, 1, 2,..., 10, that could appear in the stream, but only four of them have actually appeared. To make our estimate of the count of distinct elements, we hash each element to a 4-bit binary number. The element x is hashed to 3x + 7 (modulo 11). For example, element 8 hashes to 3*8+7 = 31, which is 9 modulo 11 (i.e., the remainder of 31/11 is 9). Thus, the 4-bit string for element 8 is 1001.
A set of four of the elements 1 through 10 could give an estimate that is exact (if the estimate is 4), or too high, or too low. You should figure out under what circumstances a set of four elements falls into each of those categories. Then, identify in the list below the set of four elements that gives the exactly correct estimate.

1. {2, 6, 8, 10}
2. {1, 5, 8, 9}
3. {3, 4, 8, 10}
4. {4, 5, 6, 7}

In [1]:
q4 = {'a': {2, 6, 8, 10},
'b': {1, 5, 8, 9},
'c': {3, 4, 8, 10},
'd': {4, 5, 6, 7}}

In [8]:
bit_strings = {0: '0000', 1: '0001', 2: '0010', 3: '0011', 4: '0100',
               5: '0101', 6: '0110', 7: '0111', 8: '1000', 9: '1001', 
               10: '1010'}

for k in q4:
    hash_list = []
    bit_list = []
    for v in q4[k]:
        hashed = (3*v + 7) % 11
        # print v, hashed
        hash_list.append(hashed)
        bit_list.append(bit_strings[hashed])
    print k, hash_list, bit_list

a [9, 4, 2, 3] ['1001', '0100', '0010', '0011']
c [9, 4, 5, 8] ['1001', '0100', '0101', '1000']
b [9, 1, 0, 10] ['1001', '0001', '0000', '1010']
d [8, 0, 3, 6] ['1000', '0000', '0011', '0110']


<img src="images/explain3a_4.JPG">

## Question 5

<img src="images/explain3a_5.JPG">