In [14]:
import numpy as np
import pandas as pd
# import math

## Question 1

In [59]:
M1 = np.matrix([
        #M, N, P, Q, R
        [1, 2, 3, 4, 5], #A
        [2, 3, 2, 5, 3], #B
        [5, 5, 5, 3, 2]  #C
    ])

M1 = M1.astype(float)

Normalize the ratings by substracting the average for each row and then subtracting the average for each column in the resulting table.

In [60]:
# average for each row

for i in range(np.shape(M1)[0]):
    print np.mean(M1[i])

3.0
3.0
4.0


In [61]:
# substracting the average for each row

for i in range(np.shape(M1)[0]):
    M1[i] = M1[i].astype(float) - np.mean(M1[i])
    
M1

matrix([[-2., -1.,  0.,  1.,  2.],
        [-1.,  0., -1.,  2.,  0.],
        [ 1.,  1.,  1., -1., -2.]])

In [62]:
# average for each resulting column

for i in range(np.shape(M1)[1]):
    print np.mean(M1[:,i])

-0.666666666667
0.0
0.0
0.666666666667
0.0


In [63]:
# subtracting the average for each column in the resulting table

for i in range(np.shape(M1)[1]):
    M1[:,i] = M1[:,i] - np.mean(M1[:,i])
    
M1

matrix([[-1.33333333, -1.        ,  0.        ,  0.33333333,  2.        ],
        [-0.33333333,  0.        , -1.        ,  1.33333333,  0.        ],
        [ 1.66666667,  1.        ,  1.        , -1.66666667, -2.        ]])

## Question 2

Below is a table givig the profile of three items.

In [142]:
M2 = np.matrix([
        [1, 0, 1, 0, 1, 2], #A
        [1, 1, 0, 0, 1, 6], #B
        [0, 1, 0, 1, 0, 2]  #C
    ])

M2 = M2.astype(float)

The first five attributes are Boolean, and the last is an integer "rating". Assume that the scale factor for the rating is alpha. Compute, as a function of alpha, the cosine distances between each pair of profiles. For each of alpha = 0, 0.5, 1, and 2, determine the cosine of the angle between each pair of vectors. 

In [134]:
#alpha values

a = [0., 0.5, 1., 2.]

# products

A, B, C = 0, 1, 2

In [135]:
for i in a:
    print "alpha: " + str(i)
    print "rating: "
    for j in range(np.shape(M2)[0]):
        print i * M2[j, -1]

alpha: 0.0
rating: 
0.0
0.0
0.0
alpha: 0.5
rating: 
1.0
3.0
1.0
alpha: 1.0
rating: 
2.0
6.0
2.0
alpha: 2.0
rating: 
4.0
12.0
4.0


In [136]:
def cos_measure(x,y):
    nom = np.dot(x, np.transpose(y))
    denom_x = np.sum(np.square(x)) ** .5
    denom_y = np.sum(np.square(y)) ** .5
    return nom / (denom_x * denom_y)

In [148]:
for i in a:
    M2_alpha = np.array([2., 6., 2.]).reshape((3,1))
    print "alpha: " + str(i)
    M2[:,-1] = M2_alpha * i
    print M2
    print "cosine of A & B: " + str(cos_measure(M2[0], M2[1]))
    print "cosine of A & C: " + str(cos_measure(M2[0], M2[2]))
    print "cosine of B & C: " + str(cos_measure(M2[1], M2[2]))
    print ''

alpha: 0.0
[[ 1.  0.  1.  0.  1.  0.]
 [ 1.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  0.]]
cosine of A & B: [[ 0.66666667]]
cosine of A & C: [[ 0.]]
cosine of B & C: [[ 0.40824829]]

alpha: 0.5
[[ 1.  0.  1.  0.  1.  1.]
 [ 1.  1.  0.  0.  1.  3.]
 [ 0.  1.  0.  1.  0.  1.]]
cosine of A & B: [[ 0.72168784]]
cosine of A & C: [[ 0.28867513]]
cosine of B & C: [[ 0.66666667]]

alpha: 1.0
[[ 1.  0.  1.  0.  1.  2.]
 [ 1.  1.  0.  0.  1.  6.]
 [ 0.  1.  0.  1.  0.  2.]]
cosine of A & B: [[ 0.84731855]]
cosine of A & C: [[ 0.6172134]]
cosine of B & C: [[ 0.84983659]]

alpha: 2.0
[[  1.   0.   1.   0.   1.   4.]
 [  1.   1.   0.   0.   1.  12.]
 [  0.   1.   0.   1.   0.   4.]]
cosine of A & B: [[ 0.94609454]]
cosine of A & C: [[ 0.86518091]]
cosine of B & C: [[ 0.95257934]]



In [108]:
print M2[0]
print np.sum(M2[0])
print np.square(M2[0])
print np.sum(np.square(M2[0]))
print np.sum(np.square(M2[0])) ** .5

[[ 1.  0.  1.  0.  1.  2.]]
5.0
[[ 1.  0.  1.  0.  1.  4.]]
7.0
2.64575131106


In [111]:
# test
x = [1., 2., -1.]
y = [2., 1., 1.]

nom = np.dot(x, np.transpose(y))
denom_x = np.sum(np.square(x)) ** .5
denom_y = np.sum(np.square(y)) ** .5

nom, denom_x, denom_y, nom / (denom_x * denom_y)

(3.0, 2.4494897427831779, 2.4494897427831779, 0.50000000000000011)

In [113]:
math.degrees(nom / (denom_x * denom_y))

28.64788975654117

In [114]:
math.hypot(3,4)

5.0

In [115]:
math.cos(60)

-0.9524129804151563

In [119]:
math.degrees(.5)

28.64788975654116