In [1]:
import numpy as np
import pandas as pd

## Question 1

Matrix M has three rows and two columns, and the columns form an orthonormal basis. One of the columns is [2/7, 3/7, 6/7]. There are many options for the second column [x,y,z].

In [35]:
M1_c1 = np.array([[2/7., 3/7., 6/7.]])
M1_c1

array([[ 0.28571429,  0.42857143,  0.85714286]])

In [36]:
array_dict = {}
array_dict['a'] = np.array([[.890, -.346, -.297]])
array_dict['b'] = np.array([[-.548, .401, .273]])
array_dict['c'] = np.array([[.702, -.702, .117]])
array_dict['d'] = np.array([[.485, -.485, .728]])
array_dict

{'a': array([[ 0.89 , -0.346, -0.297]]),
 'b': array([[-0.548,  0.401,  0.273]]),
 'c': array([[ 0.702, -0.702,  0.117]]),
 'd': array([[ 0.485, -0.485,  0.728]])}

In [49]:
for k in array_dict:
    cand_matrix = np.concatenate((np.transpose(M1_c1),np.transpose(array_dict[k])), axis=1)
    print k
    print array_dict[k]
    print ''
    print np.dot(np.transpose(cand_matrix),cand_matrix)
    print ''

a
[[ 0.89  -0.346 -0.297]]

[[ 1.         -0.14857143]
 [-0.14857143  1.000025  ]]

c
[[ 0.702 -0.702  0.117]]

[[  1.00000000e+00   2.36318901e-18]
 [  2.36318901e-18   9.99297000e-01]]

b
[[-0.548  0.401  0.273]]

[[ 1.          0.24928571]
 [ 0.24928571  0.535634  ]]

d
[[ 0.485 -0.485  0.728]]

[[ 1.          0.55471429]
 [ 0.55471429  1.000434  ]]



In [47]:
np.sum(np.square(array_dict['c']))

0.99929699999999988

## Question 2

Matrix M has three rows and three columns, and the columns form an orthonormal basis. One of the columns is [2/7, 3/7, 6/7] and another is [6/7, 2/7, -3/7]. Let the third column be [x,y,z]. Since the length of the vector [x,y,z] must be 1, there is a constraint that x^2+y^2+z^2 = 1. However, there are other constraints, and these other contraints can be used to deduce facts about the ratios among x, y, and z.

In [53]:
M2 = np.transpose(
    np.matrix([
        [2/7., 3/7., 6/7.],
        [6/7., 2/7., -3/7.],
        ['x', 'y', 'z']
    ]))

M2, np.transpose(M2)

(matrix([['0.285714285714', '0.857142857143', 'x'],
         ['0.428571428571', '0.285714285714', 'y'],
         ['0.857142857143', '-0.428571428571', 'z']], 
        dtype='|S32'),
 matrix([['0.285714285714', '0.428571428571', '0.857142857143'],
         ['0.857142857143', '0.285714285714', '-0.428571428571'],
         ['x', 'y', 'z']], 
        dtype='|S32'))

// do not run

x = +/- 3/7
y = +/- 6/7
z = +/- 2/7

In [62]:
xs = [3/7., -3/7.]
ys = [6/7., -6/7.]
zs = [2/7., -2/7.]

for x in xs:
    for y in ys:
        for z in zs:
            print x,y,z
            M2_temp = np.transpose(
                np.matrix([
                    [2/7., 3/7., 6/7.],
                    [6/7., 2/7., -3/7.],
                    [x, y, z]
                ]))
            print np.dot(M2_temp, np.transpose(M2_temp))
            print ''


0.428571428571 0.857142857143 0.285714285714
[[  1.00000000e+00   7.34693878e-01  -1.07623661e-17]
 [  7.34693878e-01   1.00000000e+00   4.89795918e-01]
 [ -1.07623661e-17   4.89795918e-01   1.00000000e+00]]

0.428571428571 0.857142857143 -0.285714285714
[[  1.00000000e+00   7.34693878e-01  -2.44897959e-01]
 [  7.34693878e-01   1.00000000e+00  -6.23084351e-18]
 [ -2.44897959e-01   2.15247321e-17   1.00000000e+00]]

0.428571428571 -0.857142857143 0.285714285714
[[  1.00000000e+00   4.53152255e-18  -1.07623661e-17]
 [  4.53152255e-18   1.00000000e+00  -6.23084351e-18]
 [ -1.07623661e-17   2.15247321e-17   1.00000000e+00]]

0.428571428571 -0.857142857143 -0.285714285714
[[  1.00000000e+00   4.53152255e-18  -2.44897959e-01]
 [  4.53152255e-18   1.00000000e+00   4.89795918e-01]
 [ -2.44897959e-01   4.89795918e-01   1.00000000e+00]]

-0.428571428571 0.857142857143 0.285714285714
[[  1.00000000e+00   4.53152255e-18  -2.44897959e-01]
 [  4.53152255e-18   1.00000000e+00   4.89795918e-01]
 [ -2.

// do not run

y = -2x

## Question 3

Suppose we have three points in a two dimensional space: (1,1), (2,2), and (3,4). We want to perform PCA on these points, so we construct a 2-by-2 matrix whose eigenvectors are the directions that best represent these three points. Construct this matrix and identify

// do not run

(14 - lambda)(21 - lambda) - 17^2 = 0
lambda^2 - 35lambda + 294 - 289 = 0
lambda^2 - 35lambda + 5 = 0


In [3]:
# creating square matrix to identify eigenpairs

M3 = np.matrix([
        [1,1],
        [2,2],
        [3,4]
    ])

M3_T = np.transpose(M3)
M3_T

M3_matrix = np.dot(M3_T,M3)
M3_matrix

matrix([[14, 17],
        [17, 21]])

In [6]:
# Frobenius Norm for use in determining eigenpairs by power iteration

def frob_norm(v):
    return (np.sum(np.square(v))) ** .5
    

In [7]:
# naive power iteration to approximate eigenvector

def power_it_naive(M):
    # count = 0
    x0 = np.transpose(np.matrix([1,1]))
    x1 = np.dot(M, x0)/frob_norm(np.dot(M, x0))
    x2 = np.dot(M, x1)/frob_norm(np.dot(M, x1))
    x3 = np.dot(M, x2)/frob_norm(np.dot(M, x2))
    x4 = np.dot(M, x3)/frob_norm(np.dot(M, x3))
    return x4

In [8]:
eig_VEC_3a = power_it_naive(M3_matrix)
eig_VEC_3a

matrix([[ 0.63180182],
        [ 0.77512996]])

In [9]:
eig_VAL_3a = float(np.dot(np.dot(np.transpose(eig_VEC_3a),M3_matrix), eig_VEC_3a))
eig_VAL_3a

34.85655495770978

In [10]:
# identify new matrix, M* or M3_prime, to find second eigenpair

M3_prime = M3_matrix - (eig_VAL_3a * np.dot(eig_VEC_3a, np.transpose(eig_VEC_3a)))
M3_prime

matrix([[ 0.08618558, -0.07024913],
        [-0.07024913,  0.05725947]])

In [11]:
eig_VEC_3b = power_it_naive(M3_prime)
eig_VEC_3b

matrix([[ 0.77512996],
        [-0.63180183]])

In [12]:
eig_VAL_3b = float(np.dot(np.dot(np.transpose(eig_VEC_3b),M3_prime), eig_VEC_3b))
eig_VAL_3b

0.14344504229021982

In [13]:
eig_VAL_3a * eig_VAL_3b, eig_VAL_3a + eig_VAL_3b

(5.000000000000051, 35.0)

In [19]:
# E3 = eig_VEC_3a with eig_VEC_3b
E3 = np.concatenate((eig_VEC_3a, eig_VEC_3b), axis=1)
E3

matrix([[ 0.63180182,  0.77512996],
        [ 0.77512996, -0.63180183]])

In [69]:
np.dot(E3, np.transpose(E3))

matrix([[  9.99999993e-01,  -1.42585682e-09],
        [ -1.42585682e-09,   1.00000001e+00]])

In [20]:
# combine eigenvectors into 2x2 matrix

np.dot(M3,E3)

matrix([[ 1.40693178,  0.14332813],
        [ 2.81386357,  0.28665627],
        [ 4.99592531, -0.20181742]])

In [71]:
np.dot(M3_matrix, eig_VEC_3a), eig_VAL_3a * eig_VEC_3a

(matrix([[ 22.02243486],
         [ 27.01836017]]), matrix([[ 22.02243486],
         [ 27.01836017]]))

In [72]:
np.dot(M3_matrix, eig_VEC_3b), eig_VAL_3b * eig_VEC_3b

(matrix([[ 0.11118839],
         [-0.09062903]]), matrix([[ 0.11118855],
         [-0.09062884]]))

## Question 4

Find, in the list below, the vector that is orthogonal to the vector [1,2,3]. Note: the interesting concept regarding eigenvectors is "orthonormal", that is unit vectors that are orthogonal. However, this question avoids using unit vectors to make the calculations simpler.

In [63]:
array_dict4 = {}
array_dict4['a'] = np.array([0, 2, -1])
array_dict4['b'] = np.array([-1, -1, 1])
array_dict4['c'] = np.array([1, 1/2, 1/3])
array_dict4['d'] = np.array([-1, 1, -1])
array_dict4

{'a': array([ 0,  2, -1]),
 'b': array([-1, -1,  1]),
 'c': array([1, 0, 0]),
 'd': array([-1,  1, -1])}

In [66]:
for k in array_dict4:
    print k, np.dot(np.transpose(array_dict4[k]), np.array([1,2,3]))

a 1
c 1
b 0
d -2
