In [1]:
import numpy as np
from collections import defaultdict

## Question 1

Using the matrix-vector multiplication described in Section 2.3.1, applied to the matrix:

1	2	3	4<br>
5	6	7	8<br>
9	10	11	12<br>
13	14	15	16

and vector:
1
2
3
4

<img src="images/6a_1.JPG">

apply the Map function to this matrix and vector. Then, identify in the list below, one of the key-value pairs that are output of Map.

(3,110)<br>
(4,48)<br>
(4,150)<br>
(1,9)

In [40]:
M1 = np.matrix([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9,10,11,12],
        [13,14,15,16]
    ])
M1

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [41]:
v1 = np.array([1, 2, 3, 4])
v1

array([1, 2, 3, 4])

<img src="images/text_2.3.1.JPG">

In [43]:
keys = range(4)

x_i = 1

map1 = []

for i in keys:
    for j in keys:
        print (x_i, M1[i,j] * v1[j])
        map1.append((x_i, M1[i,j] * v1[j]))
    x_i += 1

(1, 1)
(1, 4)
(1, 9)
(1, 16)
(2, 5)
(2, 12)
(2, 21)
(2, 32)
(3, 9)
(3, 20)
(3, 33)
(3, 48)
(4, 13)
(4, 28)
(4, 45)
(4, 64)


## answer: (1, 9)

In [44]:
reduce1 = {k+1: 0 for k in keys}
reduce1

{1: 0, 2: 0, 3: 0, 4: 0}

In [56]:
for m in map1:
    reduce1[m[0]] += m[1]
    
reduce1

{1: 30, 2: 70, 3: 110, 4: 150}

In [14]:
np.dot(M1,v1)

matrix([[ 30,  70, 110, 150]])

## Question 2

Suppose we use the algorithm of Section 2.3.10 to compute the product of matrices M and N. Let M have x rows and y columns, while N has y rows and z columns. As a function of x, y, and z, express the answers to the following questions:

1. The output of the Map function has how many different keys? How many key-value pairs are there with each key? How many key-value pairs are there in all?
2. The input to the Reduce function has how many keys? What is the length of the value (a list) associated with each key?

Then, identify the true statement in the list below.

1. The output of the Map function has 2y pairs with each key.
2. The input to the Reduce function has pairs with lists of length xz.
3. The input to the Reduce function has pairs with lists of length 2(x+z).
4. The output of the Map function has 2y(x+z) pairs with each key.

<img src="images/text_2.3.10_map.JPG">

In [2]:
M2 = np.matrix([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9,10,11,12]
    ])

N2 = np.matrix([
        [1, 5],
        [2, 6],
        [3, 7],
        [4, 8]
    ])
print M2
print N2
print np.dot(M2,N2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[ 30  70]
 [ 70 174]
 [110 278]]


In [20]:
def map_Q2(M,N):
    
    map_M = []
    map_N = []
    
    x, y = np.shape(M)
    x = int(x) # i
    y = int(y) # j
    z = int(np.shape(N)[1]) # k
    
    for k in range(z):
        for i in range(x):
            for j in range(y):
                map_M.append((((i+1,k+1), ('M',j+1,M[i,j]))))
                
    for k in range(z):
        for i in range(x):
            for j in range(y):
                map_N.append((((i+1,k+1), ('N',j+1,N[j,k]))))
            
    return map_M, map_N

map_Q2(M2,N2)

([((1, 1), ('M', 1, 1)),
  ((1, 1), ('M', 2, 2)),
  ((1, 1), ('M', 3, 3)),
  ((1, 1), ('M', 4, 4)),
  ((2, 1), ('M', 1, 5)),
  ((2, 1), ('M', 2, 6)),
  ((2, 1), ('M', 3, 7)),
  ((2, 1), ('M', 4, 8)),
  ((3, 1), ('M', 1, 9)),
  ((3, 1), ('M', 2, 10)),
  ((3, 1), ('M', 3, 11)),
  ((3, 1), ('M', 4, 12)),
  ((1, 2), ('M', 1, 1)),
  ((1, 2), ('M', 2, 2)),
  ((1, 2), ('M', 3, 3)),
  ((1, 2), ('M', 4, 4)),
  ((2, 2), ('M', 1, 5)),
  ((2, 2), ('M', 2, 6)),
  ((2, 2), ('M', 3, 7)),
  ((2, 2), ('M', 4, 8)),
  ((3, 2), ('M', 1, 9)),
  ((3, 2), ('M', 2, 10)),
  ((3, 2), ('M', 3, 11)),
  ((3, 2), ('M', 4, 12))],
 [((1, 1), ('N', 1, 1)),
  ((1, 1), ('N', 2, 2)),
  ((1, 1), ('N', 3, 3)),
  ((1, 1), ('N', 4, 4)),
  ((2, 1), ('N', 1, 1)),
  ((2, 1), ('N', 2, 2)),
  ((2, 1), ('N', 3, 3)),
  ((2, 1), ('N', 4, 4)),
  ((3, 1), ('N', 1, 1)),
  ((3, 1), ('N', 2, 2)),
  ((3, 1), ('N', 3, 3)),
  ((3, 1), ('N', 4, 4)),
  ((1, 2), ('N', 1, 5)),
  ((1, 2), ('N', 2, 6)),
  ((1, 2), ('N', 3, 7)),
  ((1, 2), ('N', 4

<img src="images/text_2.3.10_red.JPG">

In [21]:
mapM, mapN = map_Q2(M2,N2)

In [27]:
# will not use sort feature for this (toy) set

def red_Q2(mapM, mapN):
    reduce_dict = defaultdict(list)
    
    for m in mapM:
        for n in mapN:
            
            keyM = m[0]
            valMj = m[1][1]
            m_ij = m[1][2]
            
            keyN = n[0]
            valNj = n[1][1]
            n_jk = n[1][2]
            
            if keyM == keyN and valMj == valNj:
                reduce_dict[keyM].append(m_ij * n_jk)

    for ik in reduce_dict:
        reduce_dict[ik] = sum(reduce_dict[ik])
                
    return reduce_dict


red_Q2(mapM, mapN)          

defaultdict(<type 'list'>, {(1, 2): 70, (3, 2): 278, (3, 1): 110, (2, 1): 70, (2, 2): 174, (1, 1): 30})

## Question 3

Suppose we use the two-stage algorithm of Section 2.3.9 to compute the product of matrices M and N. Let M have x rows and y columns, while N has y rows and z columns. As a function of x, y, and z, express the answers to the following questions:

1. The output of the first Map function has how many different keys? How many key-value pairs are there with each key? How many key-value pairs are there in all?
2. The output of the first Reduce function has how many keys? What is the length of the value (a list) associated with each key?
3. The output of the second Map function has how many different keys? How many key-value pairs are there with each key? How many key-value pairs are there in all?

Then, identify the true statement in the list below.

1. The output of the first Reduce function has y pairs.
2. The output of the second Map function has yz different keys.
3. The output of the first Reduce function has x+z pairs.
4. The output of the first Reduce function has x pairs.

In [82]:
# map(M) results in y different keys: (y,(M,x,m_xy))
# map(N) results in y different keys: (y,(N,z,n_yz))

# key-value pairs for each key: x for M; z for N
# how many key-value pairs in total: y*x + y*z

# first Reduce function has how many keys: x*z
# length of value (a list): 1

# output of the second Map function has how many different keys: x*z (identity)
# how many key-value pairs with each key: 1
# how many key-value pairs in all: x*z

<img src="images/text_2.3.9_mapred1a.JPG">
<img src="images/text_2.3.9_mapred1b.JPG">

In [46]:
M3 = np.matrix([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 2, 2, 6]
    ])

N3 = np.matrix([
        [1, 5],
        [2, 6],
        [3, 7],
        [4, 8]
    ])
print M3
print N3
print np.dot(M3,N3)

[[1 2 3 4]
 [5 6 7 8]
 [2 2 2 6]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[ 30  70]
 [ 70 174]
 [ 36  84]]


In [47]:
def map1(M,N):
    map_M = []
    map_N = []
    
    for y in range(int(np.shape(M)[1])):
        for x in range(int(np.shape(M)[0])):
            map_M.append((y+1, ('M', x+1, M[x,y])))
            
    for y in range(int(np.shape(N)[0])):
        for z in range(int(np.shape(N)[1])):
            map_N.append((y+1, ('N', z+1, N[y,z])))
    
    return map_M, map_N

In [48]:
map1_M, map1_N = map1(M3,N3)

In [49]:
map1_M, map1_N

([(1, ('M', 1, 1)),
  (1, ('M', 2, 5)),
  (1, ('M', 3, 2)),
  (2, ('M', 1, 2)),
  (2, ('M', 2, 6)),
  (2, ('M', 3, 2)),
  (3, ('M', 1, 3)),
  (3, ('M', 2, 7)),
  (3, ('M', 3, 2)),
  (4, ('M', 1, 4)),
  (4, ('M', 2, 8)),
  (4, ('M', 3, 6))],
 [(1, ('N', 1, 1)),
  (1, ('N', 2, 5)),
  (2, ('N', 1, 2)),
  (2, ('N', 2, 6)),
  (3, ('N', 1, 3)),
  (3, ('N', 2, 7)),
  (4, ('N', 1, 4)),
  (4, ('N', 2, 8))])

In [59]:
def red1(M,N):
    red_MN = []
    
    for m in M:
        for n in N:
            if m[0] == n[0]:
                x = m[1][1]
                m_xy = m[1][2]
                # y NOT needed, already checked for in if-statement
                z = n[1][1]
                n_yz = n[1][2]
                red_MN.append(((x,z), m_xy * n_yz))
                
    return red_MN

In [60]:
red1(map1_M,map1_N)

[((1, 1), 1),
 ((1, 2), 5),
 ((2, 1), 5),
 ((2, 2), 25),
 ((3, 1), 2),
 ((3, 2), 10),
 ((1, 1), 4),
 ((1, 2), 12),
 ((2, 1), 12),
 ((2, 2), 36),
 ((3, 1), 4),
 ((3, 2), 12),
 ((1, 1), 9),
 ((1, 2), 21),
 ((2, 1), 21),
 ((2, 2), 49),
 ((3, 1), 6),
 ((3, 2), 14),
 ((1, 1), 16),
 ((1, 2), 32),
 ((2, 1), 32),
 ((2, 2), 64),
 ((3, 1), 24),
 ((3, 2), 48)]

<img src="images/text_2.3.9_mapred2.JPG">

In [61]:
def map2(xz):
    map_XZ = defaultdict(list)
    for key,value in xz:
        map_XZ[key].append(value)
    return map_XZ

In [62]:
pre_sum = map2(red1(map1_M,map1_N))
pre_sum

defaultdict(<type 'list'>, {(1, 2): [5, 12, 21, 32], (3, 2): [10, 12, 14, 48], (3, 1): [2, 4, 6, 24], (2, 1): [5, 12, 21, 32], (2, 2): [25, 36, 49, 64], (1, 1): [1, 4, 9, 16]})

In [121]:
# sum(pre_sum[(1,1)])

for k in pre_sum:
    print (k, pre_sum[k])

((1, 2), [5, 12, 21, 32])
((3, 2), [45, 60, 77, 96])
((3, 1), [9, 20, 33, 48])
((2, 1), [5, 12, 21, 32])
((2, 2), [25, 36, 49, 64])
((1, 1), [1, 4, 9, 16])


In [122]:
def red2(xz):
    red_sum = []
    for key in xz:
        red_sum.append(((key), sum(xz[key])))
    return red_sum

In [123]:
red2(map2(red1(map1_M,map1_N)))

[((1, 2), 70),
 ((3, 2), 278),
 ((3, 1), 110),
 ((2, 1), 70),
 ((2, 2), 174),
 ((1, 1), 30)]

## Question 4

Suppose we have the following relations:
<img src="images/6a_4.JPG">
and we take their natural join by the algorithm of Section 2.3.7. Apply the Map function to the tuples of these relations. Then, construct the elements that are input to the Reduce function. Identify one of these elements in the list below.

1. (0, [(S,1)])
2. (1,(S,2))
3. (2,(R,1))
4. (1, [(S,2)])

<img src="images/text_2.3.7_join.JPG">

In [50]:
R = [(0,1), (1,2), (2,3)]
S = [(0,1), (1,2), (2,3)]

In [51]:
# natural join Map Function for R

map_R = []

for r in R:
    map_R.append((r[1],('R',r[0])))

map_R

[(1, ('R', 0)), (2, ('R', 1)), (3, ('R', 2))]

In [52]:
# natural join Map Function for S

map_S = []

for s in S:
    map_S.append((s[0],('S',s[1])))

map_S

[(0, ('S', 1)), (1, ('S', 2)), (2, ('S', 3))]

In [54]:
# construct list to be passed to reducer

map_RS = []

for i in range(4):
    temp = (i, [])
    for r in map_R:
        if i == r[0]:
            temp[1].append(r[1])
    for s in map_S:
        if i == s[0]:
            temp[1].append(s[1])
            
    map_RS.append(temp)
            
print map_RS

[(0, [('S', 1)]), (1, [('R', 0), ('S', 2)]), (2, [('R', 1), ('S', 3)]), (3, [('R', 2)])]


## answer: (0, [('S', 1)])
from above output list

In [58]:
reduce_RS = []

for rs in map_RS:
    pairs = rs[1]
    if len(pairs) > 1:
        a = pairs[0][1]
        b = rs[0]
        c = pairs[1][1]
        
        reduce_RS.append((a,b,c))
            
reduce_RS

[(0, 1, 2), (1, 2, 3)]