In [1]:
import numpy as np
from collections import defaultdict

## Question 1

Suppose we have an LSH family h of (d1,d2,.6,.4) hash functions. We can use three functions from h and the AND-construction to form a (d1,d2,w,x) family, and we can use two functions from h and the OR-construction to form a (d1,d2,y,z) family. Calculate w, x, y, and z, and then identify the correct value of one of these in the list below.

1. w=.936
2. x=.784
3. y=.36
4. y=.84

In [1]:
h = ('d1','d2',.6,.4)

In [5]:
def h_AND(h, r):
    d1 = h[0]
    d2 = h[1]
    p1 = h[2]
    p2 = h[3]
    return (d1, d2, p1**r, p2**r)
    

In [6]:
h_AND(h,3)

('d1', 'd2', 0.21599999999999997, 0.06400000000000002)

In [7]:
def h_OR(h, b):
    d1 = h[0]
    d2 = h[1]
    p1 = h[2]
    p2 = h[3]
    return (d1, d2, 1.-(1.-p1)**b, 1.-(1.-p2)**b)

In [9]:
h_OR(h, 2)

('d1', 'd2', 0.84, 0.64)

## answer: y=.84
<img src="images/andofhash.JPG">
<img src="images/orofhash.JPG">

## Question 2

Here are eight strings that represent sets:

s1 = abcef
s2 = acdeg
s3 = bcdefg
s4 = adfg
s5 = bcdfgh
s6 = bceg
s7 = cdfg
s8 = abcd

Suppose our upper limit on Jaccard distance is 0.2, and we use the indexing scheme of Section 3.9.4 based on symbols appearing in the prefix (no position or length information). For each of s1, s3, and s6, determine how many other strings that string will be compared with, if it is used as the probe string. Then, identify the true count from the list below.

1. s1 is compared with 6 other strings.
2. s1 is compared with 5 other strings.
3. s6 is compared with 2 other strings.
4. s3 is compared with 2 other strings.

<img src="images/preofstr.JPG">

In [6]:
str_sets = {'s1': 'abcef', 's2': 'acdeg', 's3': 'bcdefg', 's4': 'adfg',
            's5': 'bcdfgh', 's6': 'bceg', 's7': 'cdfg', 's8': 'abcd'}

In [13]:
# Jaccard distance
J = 0.2

In [28]:
str_comp = defaultdict(list)

for s in str_sets:
    L = len(str_sets[s])
    pos = int(J*L) + 1
    idx = str_sets[s][:pos]
    for a in idx:
        str_comp[a].append(s)
    
    # print s, L, J*L, pos, idx
    
print str_comp

defaultdict(<type 'list'>, {'a': ['s8', 's2', 's1', 's4'], 'c': ['s3', 's2', 's7', 's5'], 'b': ['s3', 's1', 's6', 's5']})


## answer: s1 is compared with 6 other strings.

## Question 3

Consider the link graph
<img src="images/otc_pagerank4.gif">
First, construct the L, the link matrix, as discussed in Section 5.5 on the HITS algorithm. Then do the following:

1. Start by assuming the hubbiness of each node is 1; that is, the vector h is (the transpose of) [1,1,1,1].
2. Compute an estimate of the authority vector a=LTh.
3. Normalize a by dividing all values so the largest value is 1.
4.  an estimate of the hubbiness vector h=La.
5. Normalize h by dividing all values so the largest value is 1.
6. Repeat steps 2-5.

Now, identify in the list below the true statement about the final estimates.

The final estimate of the hubbiness of 3 is 1. <br>
The final estimate of the hubbiness of 1 is 1/5. <br>
The final estimate of the hubbiness of 1 is 1/8. <br>
The final estimate of the authority of 2 is 3/5.

In [2]:
L = np.matrix([
        [0, 1, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]
    ])
L

matrix([[0, 1, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]])

In [3]:
L_t = np.transpose(L)
L_t

matrix([[0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [0, 0, 1, 0]])

In [4]:
h = np.ones((4,1))
h

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [6]:
a = np.dot(L_t,h)
a

matrix([[ 1.],
        [ 1.],
        [ 2.],
        [ 1.]])

In [9]:
# estimate 1 of authority
a = a / np.max(a)
a

matrix([[ 0.5],
        [ 0.5],
        [ 1. ],
        [ 0.5]])

In [10]:
# estimate 1 of hubbiness
h = np.dot(L,a)
h

matrix([[ 1.5],
        [ 0.5],
        [ 0.5],
        [ 1. ]])

In [12]:
h = h / np.max(h)
h

matrix([[ 1.        ],
        [ 0.33333333],
        [ 0.33333333],
        [ 0.66666667]])

In [13]:
# estimate 2 of authority
a = np.dot(L_t,h)
a = a / np.max(a)
a

matrix([[ 0.2],
        [ 0.6],
        [ 1. ],
        [ 0.2]])

In [14]:
# estimate 2 of hubbiness
h = np.dot(L,a)
h = h / np.max(h)
h

matrix([[ 1.   ],
        [ 0.125],
        [ 0.125],
        [ 0.625]])

## answer: The final estimate of the authority of 2 is 3/5.

## Question 4

Consider an implementation of the Block-Stripe Algorithm discussed in Section 5.2 to compute page rank on a graph of N nodes (i.e., Web pages). Suppose each page has, on average, 20 links, and we divide the new rank vector into k blocks (and correspondingly, the matrix M into k stripes). Each stripe of M has one line per "source" web page, in the format:
<br><center>[source_id, degree, m, dest_1, ...., dest_m]</center>

Notice that we had to add an additional entry, m, to denote the number of destination nodes in this stripe, which of course is no more than the degree of the node. Assume that all entries (scores, degrees, identifiers,...) are encoded using 4 bytes.

There is an additional detail we need to account for, namely, <b>locality</b> of links. As a very simple model, assume that we divide web pages into two disjoint sets:

1. <b>Introvert</b> pages, which link only to other pages within the same host as themselves.

2. <b>Extrovert</b> pages, which have links to pages across several hosts.

Assume a fraction x of pages (0 Construct a formula that counts the amount of I/O per page rank iteration in terms of N, x, and k. The 4-tuples below list combinations of N, k, x, and I/O (in bytes). Pick the correct combination.

<b>Note.</b> There are some additional optimizations one can think of, such as striping the old score vector, encoding introvert and extrovert pages using different schemes, etc. For the purposes of working this problem, assume we don't do any optimizations beyond the block-stripe algorithm discussed in class.

N = 1 billion, k = 2, x = 0.75, 112GB <br>
N = 1 billion, k = 2, x = 0.5, 110GB <br>
N = 1 billion, k = 3, x = 0.5, 132GB <br>
N = 1 billion, k = 3, x = 0.5, 124GB

In [16]:
# N nodes
# k stripes of M / blocks of the vector
# x fraction of pages

In [17]:
4 * 23

92

In [18]:
bytes = 4
stripe_len = 23


In [20]:
base_GB = bytes * stripe_len
base_GB

92

In [21]:
base_GB * .25

23.0

In [22]:
combos = [(2,0.75), (2,0.5), (3,0.5), (3,0.5)]

In [26]:
for c in combos:
    k = c[0]
    x = c[1]
    GB = base_GB*x + (base_GB*(1-x))*k
    print "k = " + str(k), "x = " + str(x), str(GB) + "GB"

k = 2 x = 0.75 115.0GB
k = 2 x = 0.5 138.0GB
k = 3 x = 0.5 184.0GB
k = 3 x = 0.5 184.0GB


<b>Question Explanation</b>

The number of bytes involved in reading the old pagerank vector and writing the new pagerank vector to disk = 4 (k+1) N For the M matrix: 

- The introvert pages will appear xN times and each row will have on average 23 entries (3 metadata and 20 destination links). Total number of bytes read = 4(23)(xN)
- The extrovert pages will appear (1-x) kN times and each row will have 3 (metadata) + 20/k (destination links) entries on average. Total number of bytes read = 4 * (3+20/k) * (1-x) kN 

Total I/O per pagerank iteration (in GB, where 1GB ~ 10^9 = N bytes) <br>= 4 [(k+1) N + 23 xN + (3k + 20) (1-x) N] / N <br>= 4 [(k+1) + 23 x + (3k + 20) (1-x)] <br>= 4 [21 + k + 3 (x + (1-x) k)]